# Generated by Django 6.0.2 on 2026-03-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAlertScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bank_alerts/')),
                ('extracted_text', models.TextField(blank=True)),
                ('risk_level', models.CharField(max_length=20)),
                ('confidence', models.IntegerField(default=0)),
                ('reasons', models.JSONField(default=list)),
                ('state', models.CharField(choices=[('lagos', 'Lagos'), ('abuja', 'Abuja'), ('kano', 'Kano'), ('rivers', 'Rivers'), ('oyo', 'Oyo'), ('delta', 'Delta'), ('anambra', 'Anambra'), ('enugu', 'Enugu'), ('kaduna', 'Kaduna'), ('ogun', 'Ogun'), ('imo', 'Imo'), ('borno', 'Borno'), ('katsina', 'Katsina'), ('edo', 'Edo'), ('cross_river', 'Cross River'), ('akwa_ibom', 'Akwa Ibom'), ('sokoto', 'Sokoto'), ('osun', 'Osun'), ('ondo', 'Ondo'), ('benue', 'Benue'), ('adamawa', 'Adamawa'), ('ekiti', 'Ekiti'), ('kwara', 'Kwara'), ('niger', 'Niger'), ('plateau', 'Plateau'), ('taraba', 'Taraba'), ('nasarawa', 'Nasarawa'), ('gombe', 'Gombe'), ('zamfara', 'Zamfara'), ('kebbi', 'Kebbi'), ('jigawa', 'Jigawa'), ('yobe', 'Yobe'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('ebonyi', 'Ebonyi'), ('abia', 'Abia'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScamPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=200)),
                ('keywords', models.JSONField(default=list)),
                ('scam_type', models.CharField(max_length=50)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('confidence_score', models.FloatField(default=0.5)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('scam_type', models.CharField(choices=[('investment', 'Investment Fraud'), ('bank_impersonation', 'Bank Impersonation'), ('job_scam', 'Fake Job Offer'), ('lottery', 'Lottery Scam'), ('romance', 'Romance Scam'), ('phishing', 'Phishing'), ('fake_alert', 'Fake Bank Alert'), ('crypto', 'Crypto Scam'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='scam_screenshots/')),
                ('state', models.CharField(choices=[('lagos', 'Lagos'), ('abuja', 'Abuja'), ('kano', 'Kano'), ('rivers', 'Rivers'), ('oyo', 'Oyo'), ('delta', 'Delta'), ('anambra', 'Anambra'), ('enugu', 'Enugu'), ('kaduna', 'Kaduna'), ('ogun', 'Ogun'), ('imo', 'Imo'), ('borno', 'Borno'), ('katsina', 'Katsina'), ('edo', 'Edo'), ('cross_river', 'Cross River'), ('akwa_ibom', 'Akwa Ibom'), ('sokoto', 'Sokoto'), ('osun', 'Osun'), ('ondo', 'Ondo'), ('benue', 'Benue'), ('adamawa', 'Adamawa'), ('ekiti', 'Ekiti'), ('kwara', 'Kwara'), ('niger', 'Niger'), ('plateau', 'Plateau'), ('taraba', 'Taraba'), ('nasarawa', 'Nasarawa'), ('gombe', 'Gombe'), ('zamfara', 'Zamfara'), ('kebbi', 'Kebbi'), ('jigawa', 'Jigawa'), ('yobe', 'Yobe'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('ebonyi', 'Ebonyi'), ('abia', 'Abia'), ('other', 'Other')], max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('report_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScamScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('risk_level', models.CharField(max_length=20)),
                ('confidence', models.IntegerField(default=0)),
                ('reasons', models.JSONField(default=list)),
                ('ai_explanation', models.TextField(blank=True)),
                ('scam_type', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(choices=[('lagos', 'Lagos'), ('abuja', 'Abuja'), ('kano', 'Kano'), ('rivers', 'Rivers'), ('oyo', 'Oyo'), ('delta', 'Delta'), ('anambra', 'Anambra'), ('enugu', 'Enugu'), ('kaduna', 'Kaduna'), ('ogun', 'Ogun'), ('imo', 'Imo'), ('borno', 'Borno'), ('katsina', 'Katsina'), ('edo', 'Edo'), ('cross_river', 'Cross River'), ('akwa_ibom', 'Akwa Ibom'), ('sokoto', 'Sokoto'), ('osun', 'Osun'), ('ondo', 'Ondo'), ('benue', 'Benue'), ('adamawa', 'Adamawa'), ('ekiti', 'Ekiti'), ('kwara', 'Kwara'), ('niger', 'Niger'), ('plateau', 'Plateau'), ('taraba', 'Taraba'), ('nasarawa', 'Nasarawa'), ('gombe', 'Gombe'), ('zamfara', 'Zamfara'), ('kebbi', 'Kebbi'), ('jigawa', 'Jigawa'), ('yobe', 'Yobe'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('ebonyi', 'Ebonyi'), ('abia', 'Abia'), ('other', 'Other')], default='other', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
