# Generated by Django 6.0.2 on 2026-03-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('clean_url', models.CharField(blank=True, max_length=2000)),
                ('risk_level', models.CharField(max_length=20)),
                ('confidence', models.IntegerField(default=0)),
                ('reasons', models.JSONField(default=list)),
                ('threat_type', models.CharField(blank=True, max_length=100)),
                ('ai_explanation', models.TextField(blank=True)),
                ('is_shortener', models.BooleanField(default=False)),
                ('final_url', models.URLField(blank=True, max_length=2000)),
                ('state', models.CharField(choices=[('lagos', 'Lagos'), ('abuja', 'Abuja'), ('kano', 'Kano'), ('rivers', 'Rivers'), ('oyo', 'Oyo'), ('delta', 'Delta'), ('anambra', 'Anambra'), ('enugu', 'Enugu'), ('kaduna', 'Kaduna'), ('ogun', 'Ogun'), ('imo', 'Imo'), ('borno', 'Borno'), ('katsina', 'Katsina'), ('edo', 'Edo'), ('cross_river', 'Cross River'), ('akwa_ibom', 'Akwa Ibom'), ('sokoto', 'Sokoto'), ('osun', 'Osun'), ('ondo', 'Ondo'), ('benue', 'Benue'), ('adamawa', 'Adamawa'), ('ekiti', 'Ekiti'), ('kwara', 'Kwara'), ('niger', 'Niger'), ('plateau', 'Plateau'), ('taraba', 'Taraba'), ('nasarawa', 'Nasarawa'), ('gombe', 'Gombe'), ('zamfara', 'Zamfara'), ('kebbi', 'Kebbi'), ('jigawa', 'Jigawa'), ('yobe', 'Yobe'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('ebonyi', 'Ebonyi'), ('abia', 'Abia'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
