# Generated by Django 6.0.2 on 2026-03-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_linkscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkscan',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
